"""
OSP (one-sample-pipeline): single-sample QC → dimensionality reduction /
clustering → cluster-level DEG, end to end.

Strictly single-sample by design — no cross-sample batch integration (no
sample_col/batch_key/Harmony branches). Multi-sample integration is a
separate downstream step run after several OSP outputs exist; it does not
belong in this module.

Standard scRNA-seq clustering flow:
  HVG(seurat) → scale → PCA(50) → neighbors → leiden (flavor="igraph",
  n_iterations=2, adjustable resolution) → umap → rank_genes_groups
  (wilcoxon, use_raw=True) → per-cluster top-N DE gene table → PAGA
  (cluster-cluster connectivity over the neighbors graph).

Two API layers:
  - cluster_and_deg(adata, ...): takes an already-QC'ed single-sample adata,
    runs the full clustering/DEG/PAGA, returns (adata, de_df,
    cluster_summary_df, paga_df).
  - run_one_sample_pipeline(adata, sample_label=None, ...): takes a raw
    (pre-QC) single-sample adata, runs osp.qc.qc_one_sample → keeps only
    passing cells → calls cluster_and_deg. The one-stop entry point from QC
    through DEG.

Analysis plots are always generated by default (make_plots=True), regardless
of outdir — without an outdir they go to ./cluster_figs/. **No scanpy
multi_panel figures** — every metric / every clustering resolution gets its
own file, so each can be read/cited individually; all single UMAP panels
share one figsize/dpi/axes rect (see _UMAP_FIGSIZE etc.), non-UMAP singles
(violin/heatmap) also have fixed sizes, and page layout is osp.report's job,
not the images'. File names follow "<topic>_<column-or-resolution>.png":
  umap_clusters_{leiden_key}.png   one per leiden resolution (e.g.
                                    umap_clusters_leiden_r1.0.png)
  paga.png                         cluster connectivity graph (node=cluster,
                                    edge width=connectivity), size/position
                                    aligned with umap_clusters_{primary_key}.png
                                    for side-by-side comparison in the report
  umap_qc_{col}.png                one per QC metric (total_counts /
                                    n_genes_by_counts / pct_counts_mt /
                                    doublet_score / decontX_contamination /
                                    pct_counts_malat1 / dissociation_score —
                                    whichever columns exist)
  qc_violin_{col}.png              the same QC metrics as violins grouped by
                                    the primary clusters, one per metric
  decontx_heatmap_by_cluster.png   gene x cluster DecontX contamination-
                                    fraction heatmap (inherently one matrix
                                    image, not split)
  umap_markers_{name}.png          only when marker_genes is passed (off by
                                    default), one per cell-type marker score

Tables in the outdir root follow "<topic>_{primary_key}.csv":
  cluster_summary_{key}.csv / paga_connectivities_{key}.csv /
  decontx_top_genes_{key}.csv / de_top_genes_{key}.csv

Usage:
    from osp import run_one_sample_pipeline

    ad_fo = adata[adata.obs["sample"] == "FO"]
    ad_final, de_df, cluster_summary, paga_df, decontx_by_cluster, qc_summary = run_one_sample_pipeline(
        ad_fo, sample_label="FO", outdir="osp_out/FO"
    )

    # or, when QC was already done separately, just cluster + DEG:
    from osp import cluster_and_deg
    ad_final, de_df, cluster_summary, paga_df, decontx_by_cluster = cluster_and_deg(ad_qcpass)

    # re-cluster at other resolutions (resolutions/primary_resolution are free):
    cluster_and_deg(ad_qcpass, resolutions=(0.3, 0.5, 0.8, 1.2), primary_resolution=0.8)
"""

import os
import re

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
import scanpy as sc
import scipy.sparse as sp
from sklearn.decomposition import PCA

from .qc import assert_single_sample, cluster_order, decontx_top_genes, qc_one_sample

# OSP doesn't know what tissue/species it is given, so there is no built-in
# default marker set — marker_genes defaults to None (marker plots skipped).
# Callers with actual cell-type/marker context (an upstream pipeline) pass
# their own dict; it doesn't belong in this generic module as a default.

# z-scored and appended to the HVG z-scores as PCA input (see the
# qc_pca_covariates parameter) — whichever of these columns exist are used;
# missing ones (e.g. run_scrublet/run_decontx skipped) are ignored.
DEFAULT_QC_PCA_COVARIATES = (
    "doublet_score", "total_counts", "n_genes_by_counts", "decontX_contamination",
    "pct_counts_mt", "dissociation_score",
)


def _as_labels(x):
    """Single label (str/int/...) or a list of labels -> list of strings,
    aligned with the obs column's astype(str)."""
    if isinstance(x, str) or not hasattr(x, "__iter__"):
        return [str(x)]
    return [str(g) for g in x]


def deg_two_groups(
    adata,
    group_key,
    group1,
    group2=None,
    layer=None,
    hvg_only=True,
    n_top_genes=2000,
    tie_correct=False,
):
    """Wilcoxon DEG between two cell groups; returns a long-format DataFrame
    for reuse by callers (not limited to cluster contrasts — any categorical
    obs column works, e.g. cell-type labels or treatment groups).

    group1/group2 each accept a single label or a list of labels (values of
    the group_key column, e.g. several cluster ids merged into one group, or
    several cell types merged). With group2=None all remaining cells form the
    comparison group (one-vs-rest).

    The wilcoxon runs on the HVG gene subset only (when hvg_only=True; an
    existing "highly_variable" column in adata.var is reused, otherwise it is
    computed on the fly) — not a genome-wide scan, so the table is shorter
    with fewer noise genes.

    Parameters
    ----------
    layer : str or None
        Layer passed to rank_genes_groups; None (default) uses adata.X
        (assumed to be normalize_total+log1p already).
    tie_correct : bool
        Wilcoxon tie correction — more accurate with few cells / many zeros,
        but slower.

    Returns
    -------
    DataFrame, one gene per row, columns:
      gene, logfc, pct1, pct2, pval, pval_adj, high_in, low_in
      (pct1/pct2 = fraction of cells expressing the gene in group1/group2;
      high_in/low_in hold the human-readable group1_label/group2_label chosen
      by the sign of logfc — not scanpy's internal temporary group names)
    """
    group1 = _as_labels(group1)
    if group2 is not None:
        group2 = _as_labels(group2)
        if set(group1) & set(group2):
            raise ValueError(f"group1/group2 overlap: {sorted(set(group1) & set(group2))}")

    labels = adata.obs[group_key].astype(str)
    mask1 = labels.isin(group1)
    mask2 = ~mask1 if group2 is None else labels.isin(group2)
    group1_label = "+".join(group1)
    group2_label = "rest" if group2 is None else "+".join(group2)

    if mask1.sum() == 0:
        raise ValueError(f"group1={group1} matches no cells in obs[{group_key!r}]")
    if mask2.sum() == 0:
        raise ValueError(f"group2={group2} matches no cells in obs[{group_key!r}]")

    keep = mask1 | mask2
    ad = adata[keep].copy()
    tmp_key = "_deg_group"
    ad.obs[tmp_key] = pd.Categorical(np.where(mask1[keep].values, group1_label, group2_label))

    if hvg_only:
        if "highly_variable" not in ad.var:
            sc.pp.highly_variable_genes(ad, n_top_genes=n_top_genes, flavor="seurat")
        ad = ad[:, ad.var["highly_variable"]].copy()

    sc.tl.rank_genes_groups(
        ad, tmp_key, groups=[group1_label], reference=group2_label,
        method="wilcoxon", layer=layer, use_raw=False, tie_correct=tie_correct,
    )
    df = sc.get.rank_genes_groups_df(ad, group=group1_label)
    df = df.rename(columns={
        "names": "gene", "logfoldchanges": "logfc", "pvals": "pval", "pvals_adj": "pval_adj",
    })

    # scanpy's pts=True only fills pct_nz_reference when reference="rest" —
    # with an explicit reference group it's left out, so compute both
    # fractions ourselves off the same (HVG-subsetted) matrix used above.
    X = ad.layers[layer] if layer else ad.X
    mat1 = X[(ad.obs[tmp_key] == group1_label).values]
    mat2 = X[(ad.obs[tmp_key] == group2_label).values]
    if sp.issparse(mat1):
        pct1 = np.asarray((mat1 != 0).sum(axis=0)).ravel() / mat1.shape[0]
        pct2 = np.asarray((mat2 != 0).sum(axis=0)).ravel() / mat2.shape[0]
    else:
        pct1 = (mat1 != 0).mean(axis=0)
        pct2 = (mat2 != 0).mean(axis=0)
    pct1 = pd.Series(pct1, index=ad.var_names)
    pct2 = pd.Series(pct2, index=ad.var_names)
    df["pct1"] = df["gene"].map(pct1)
    df["pct2"] = df["gene"].map(pct2)

    df["high_in"] = np.where(df["logfc"] > 0, group1_label, group2_label)
    df["low_in"] = np.where(df["logfc"] > 0, group2_label, group1_label)
    return df[["gene", "logfc", "pct1", "pct2", "pval", "pval_adj", "high_in", "low_in"]].sort_values(
        "logfc", ascending=False
    ).reset_index(drop=True)


def cluster_and_deg(
    adata,
    sample_col="sample",
    counts_layer="counts",
    n_top_genes=2000,
    n_pcs=50,
    n_neighbors=15,
    resolutions=(0.5, 1.0),
    primary_resolution=1.0,
    top_n_de=25,
    qc_pca_covariates=DEFAULT_QC_PCA_COVARIATES,
    outdir=None,
    make_plots=True,
    figdir=None,
    marker_genes=None,
):
    """Normalize→HVG→PCA→neighbors→Leiden→UMAP→DEG on an already-QC'ed
    single-sample adata.

    Single sample only; no batch integration (no Harmony).

    Parameters
    ----------
    adata : AnnData
        QC-passed cells of one sample. If `counts_layer` exists, X is first
        replaced with those raw counts, so an already-normalized matrix is
        never normalized twice.
    resolutions : tuple
        All leiden resolutions to compute; each is stored as
        obs["leiden_r{res}"].
    primary_resolution : float
        Which resolution's clusters feed rank_genes_groups; must be a member
        of resolutions.
    make_plots : bool
        Whether to generate the UMAP analysis plots (clusters / QC metrics /
        marker scores). Independent of outdir — without an outdir they go to
        ./cluster_figs/.
    figdir : str or None
        Directory for plots, taking precedence over outdir/figures; when
        neither is given and make_plots=True, defaults to "cluster_figs".
    marker_genes : dict[str, list[str]] or None
        {cell type: marker gene list} for marker UMAPs. Default None (plot
        skipped) — OSP doesn't know the tissue/species context, so a marker
        set must come from the caller.
    sample_col : str
        Used to verify the adata holds one sample, see assert_single_sample.
    qc_pca_covariates : tuple[str] or None
        These obs columns (whichever exist) are z-scored and appended to the
        HVG z-score matrix as joint PCA input — NOT standard practice
        (standard PCA uses HVG expression only); added by request so the
        PCA/neighbors/Leiden distance metric explicitly includes these QC
        differences instead of reflecting them only indirectly through
        expression. Pass None or () to disable and fall back to standard
        HVG-only PCA.

    Returns
    -------
    (adata, de_df, cluster_summary_df, paga_df, decontx_by_cluster_df)
      de_df: top_n_de DE genes per cluster (wilcoxon, use_raw=True, with
        pct1/pct2 expression-fraction columns)
      cluster_summary_df: per-cluster cell count and median doublet_score
      paga_df: cluster x cluster PAGA connectivity matrix
      decontx_by_cluster_df: present only when adata.layers has
        "decontX_counts" (i.e. qc_one_sample(run_decontx=True) ran upstream);
        the per-cluster contaminating-gene ranking — "which cluster is
        contaminated by which genes". Either None or the per_cluster_df of
        osp.qc.decontx_top_genes().
    """
    assert_single_sample(adata, sample_col=sample_col)

    leiden_keys = [f"leiden_r{r}" for r in resolutions]
    primary_key = f"leiden_r{primary_resolution}"
    if primary_key not in leiden_keys:
        raise ValueError(f"primary_resolution={primary_resolution} is not in resolutions={resolutions}")

    ad = adata.copy()
    if counts_layer in ad.layers:
        ad.X = ad.layers[counts_layer].copy()
    else:
        # X is about to be overwritten by normalize/log1p — stash the raw
        # counts in a layer first: decontx_top_genes / the contamination
        # heatmap need raw counts for raw - decontX_counts, and the exported
        # clustered.h5ad keeps a copy of the raw counts this way too.
        ad.layers[counts_layer] = ad.X.copy()

    print("== normalize/log1p", flush=True)
    sc.pp.normalize_total(ad, target_sum=1e4)
    sc.pp.log1p(ad)
    ad.raw = ad

    print("== HVG", flush=True)
    sc.pp.highly_variable_genes(ad, n_top_genes=n_top_genes, flavor="seurat")

    hvg = ad[:, ad.var.highly_variable].copy()
    sc.pp.scale(hvg, max_value=10)
    X_hvg = hvg.X
    n_features = X_hvg.shape[1]

    qc_cov_cols = [c for c in (qc_pca_covariates or ()) if c in ad.obs]
    if ad.uns.get("osp_decontx_degenerate") and "decontX_contamination" in qc_cov_cols:
        # qc_one_sample flagged the DecontX fit as unrecoverable — a pinned
        # 0/1 bimodal column would add a garbage axis to the PCA input
        print("== decontX contamination flagged degenerate; dropping it from PCA covariates", flush=True)
        qc_cov_cols.remove("decontX_contamination")
    if qc_cov_cols:
        print(f"== adding z-scored QC covariates to PCA input: {qc_cov_cols}", flush=True)
        qc_mat = ad.obs[qc_cov_cols].to_numpy(dtype=float)
        qc_std = qc_mat.std(axis=0, ddof=0)
        qc_std[qc_std == 0] = 1  # constant column -> z-score 0 everywhere, avoid /0
        qc_z = np.clip((qc_mat - qc_mat.mean(axis=0)) / qc_std, -10, 10)
        X_pca_input = np.hstack([X_hvg, qc_z])
        n_features += len(qc_cov_cols)
    else:
        X_pca_input = X_hvg

    n_comps = min(n_pcs, n_features - 1, ad.n_obs - 1)
    ad.obsm["X_pca"] = PCA(n_components=n_comps, svd_solver="arpack", random_state=0).fit_transform(X_pca_input)
    del hvg

    print("== neighbors (use_rep=X_pca)", flush=True)
    sc.pp.neighbors(ad, use_rep="X_pca", n_neighbors=n_neighbors)

    for res, key in zip(resolutions, leiden_keys):
        print(f"== leiden {key}", flush=True)
        sc.tl.leiden(ad, resolution=res, key_added=key, flavor="igraph", n_iterations=2)

    print("== umap", flush=True)
    sc.tl.umap(ad)

    print(f"== rank_genes_groups on {primary_key}", flush=True)
    sc.tl.rank_genes_groups(ad, primary_key, method="wilcoxon", use_raw=True, pts=True)
    de_df = sc.get.rank_genes_groups_df(ad, group=None)
    # pct1/pct2 = fraction of cells expressing (non-zero) the gene inside this
    # cluster / in all other cells; column names match deg_two_groups' output
    de_df = de_df.rename(columns={"pct_nz_group": "pct1", "pct_nz_reference": "pct2"})
    de_top = de_df.groupby("group", observed=True).head(top_n_de).reset_index(drop=True)

    cluster_summary = _cluster_summary_table(ad, primary_key)

    print(f"== paga on {primary_key}", flush=True)
    sc.tl.paga(ad, groups=primary_key)
    paga_df = _paga_table(ad, primary_key)

    decontx_by_cluster = None
    if "decontX_counts" in ad.layers:
        print(f"== decontX gene contamination by {primary_key}", flush=True)
        _, decontx_by_cluster = decontx_top_genes(ad, cluster_key=primary_key, counts_layer=counts_layer)

    if outdir:
        os.makedirs(outdir, exist_ok=True)
        de_top.to_csv(os.path.join(outdir, f"de_top_genes_{primary_key}.csv"), index=False)
        cluster_summary.to_csv(os.path.join(outdir, f"cluster_summary_{primary_key}.csv"))
        paga_df.to_csv(os.path.join(outdir, f"paga_connectivities_{primary_key}.csv"))
        if decontx_by_cluster is not None:
            decontx_by_cluster.to_csv(os.path.join(outdir, f"decontx_top_genes_{primary_key}.csv"), index=False)
        ad.write(os.path.join(outdir, "clustered.h5ad"))

    if make_plots:
        resolved_figdir = figdir or (os.path.join(outdir, "figures") if outdir else "cluster_figs")
        os.makedirs(resolved_figdir, exist_ok=True)
        _plot_cluster_overview(ad, leiden_keys, marker_genes, resolved_figdir)
        _plot_paga(ad, resolved_figdir)
        _plot_qc_violin(ad, primary_key, resolved_figdir)
        if decontx_by_cluster is not None:
            _plot_decontx_cluster_heatmap(ad, primary_key, decontx_by_cluster, counts_layer, resolved_figdir)

    return ad, de_top, cluster_summary, paga_df, decontx_by_cluster


def _cluster_summary_table(ad, cluster_key):
    """Per-cluster cell count + median doublet_score."""
    cluster_str = ad.obs[cluster_key].astype(str)
    summary = pd.DataFrame({"n_cells": cluster_str.value_counts()})
    summary.index.name = cluster_key

    if "doublet_score" in ad.obs:
        summary["median_doublet_score"] = ad.obs["doublet_score"].groupby(cluster_str, observed=True).median()

    summary = summary.reindex(cluster_order(cluster_str))
    summary.index.name = cluster_key
    return summary


# Every individual plot (one file per metric/cluster/etc — no scanpy
# multi_panel figures, see module docstring) shares these constants so a
# human/agent looking at the figures directory sees consistently-sized
# images, and any two UMAP panels line up exactly if placed side by side in
# the report (same figsize/dpi/axes-rect, not just "roughly the same size").
_UMAP_FIGSIZE = (5.5, 5.5)
_UMAP_AXES_RECT = (0.14, 0.12, 0.78, 0.78)  # left, bottom, width, height (figure fraction)
_UMAP_DPI = 150
_PLOT_FIGSIZE = (6, 4.5)  # non-UMAP single-axes plots (violin, histograms, ...)
_PLOT_DPI = 150


def _slug(name):
    """Filesystem-safe stand-in for an obs column / cluster key, used as a
    filename suffix. Leiden keys ("leiden_r1.0") and obs column names
    ("decontX_contamination") are already filename-safe, so this is mostly
    a defensive fallback for arbitrary marker_genes keys."""
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(name))


def _square_limits(xy, pad=1.05):
    xmin, ymin = xy.min(axis=0)
    xmax, ymax = xy.max(axis=0)
    cx, cy = (xmin + xmax) / 2, (ymin + ymax) / 2
    half = max(xmax - xmin, ymax - ymin) / 2 * pad
    return (cx - half, cx + half), (cy - half, cy + half)


def _save_single_umap(ad, color_col, out_path, **kwargs):
    """One UMAP colored by one column, saved to its own file — no scanpy
    multi_panel figures (harder for a human/agent to read one signal off of
    a combined image). Fixed figsize/axes-rect so every UMAP panel this
    pipeline produces is pixel-for-pixel comparable.
    """
    xlim, ylim = _square_limits(ad.obsm["X_umap"])
    kwargs.setdefault("size", 120000 / ad.n_obs)

    fig = plt.figure(figsize=_UMAP_FIGSIZE)
    ax = fig.add_axes(_UMAP_AXES_RECT)
    sc.pl.umap(ad, color=color_col, ax=ax, show=False, **kwargs)
    ax.set_xlim(*xlim)
    ax.set_ylim(*ylim)
    ax.set_aspect("equal", adjustable="box")
    # scanpy clears tick *positions* (set_xticks([])), so tick_params alone
    # can't bring them back; reset the locator first.
    ax.xaxis.set_major_locator(mticker.AutoLocator())
    ax.yaxis.set_major_locator(mticker.AutoLocator())
    ax.tick_params(left=True, bottom=True, labelleft=True, labelbottom=True)
    # "UMAP1"/"UMAP2" axis labels are redundant once there's one file per
    # panel; say it once via the title instead.
    ax.set_xlabel("")
    ax.set_ylabel("")
    ax.set_title(f"UMAP: {ax.get_title()}")
    fig.savefig(out_path, dpi=_UMAP_DPI)
    plt.close(fig)


def _save_umap_panels(ad, color_cols, prefix, figdir, **kwargs):
    """_save_single_umap for each column, named "{prefix}_{slug(col)}.png"."""
    paths = []
    for col in color_cols:
        out_path = os.path.join(figdir, f"{prefix}_{_slug(col)}.png")
        _save_single_umap(ad, col, out_path, **kwargs)
        paths.append(out_path)
    return paths


def _plot_paga(ad, figdir):
    """PAGA graph, sized/positioned identically to the umap_clusters_*.png
    panels (see _UMAP_FIGSIZE/_UMAP_AXES_RECT) so it lines up when placed
    next to the primary-resolution cluster UMAP in the report."""
    print(f"== plotting PAGA -> {figdir}", flush=True)

    fig = plt.figure(figsize=_UMAP_FIGSIZE)
    ax = fig.add_axes(_UMAP_AXES_RECT)
    sc.pl.paga(ad, ax=ax, show=False)
    # sc.pl.paga computes/caches the node layout into uns["paga"]["pos"] the
    # first time it's called (the call above) — reuse it to get square,
    # symmetric limits the same way _square_limits does for the UMAP.
    xlim, ylim = _square_limits(np.asarray(ad.uns["paga"]["pos"]))
    ax.set_xlim(*xlim)
    ax.set_ylim(*ylim)
    ax.set_aspect("equal", adjustable="box")
    fig.savefig(os.path.join(figdir, "paga.png"), dpi=_UMAP_DPI)
    plt.close(fig)


def _plot_decontx_cluster_heatmap(ad, cluster_key, decontx_by_cluster, counts_layer, figdir, top_n_genes=20):
    """Gene (rows) x cluster (columns) contamination-fraction heatmap —
    answers "which cluster is contaminated by which genes" instead of one
    aggregate score. Rows are the union of genes appearing in the per-cluster
    contamination rankings (truncated to top_n_genes by amount); columns show
    each cluster's contamination fraction for those genes (what share of that
    gene's UMIs in that cluster decontX judged ambient). The cross-cluster
    difference for the same gene is the clue to the contamination source."""
    top_genes = (
        decontx_by_cluster.sort_values("contam_counts", ascending=False)["gene"]
        .drop_duplicates()
        .head(top_n_genes)
        .tolist()
    )
    if not top_genes:
        return

    raw = sp.csr_matrix(ad.layers[counts_layer] if counts_layer in ad.layers else ad.X)
    decon = sp.csr_matrix(ad.layers["decontX_counts"])
    removed = raw - decon
    removed.data = np.clip(removed.data, 0, None)
    removed.eliminate_zeros()

    gene_idx = [ad.var_names.get_loc(g) for g in top_genes]
    groups = ad.obs[cluster_key].astype(str)
    clusters = cluster_order(groups)
    frac = np.zeros((len(top_genes), len(clusters)))
    for j, cl in enumerate(clusters):
        mask = (groups == cl).values
        gene_removed = np.asarray(removed[mask][:, gene_idx].sum(axis=0)).ravel()
        gene_raw = np.asarray(raw[mask][:, gene_idx].sum(axis=0)).ravel()
        frac[:, j] = gene_removed / np.maximum(gene_raw, 1)

    fig, ax = plt.subplots(figsize=(max(6, 0.5 * len(clusters)), max(4, 0.35 * len(top_genes))))
    im = ax.imshow(frac, aspect="auto", cmap="magma", vmin=0, vmax=frac.max() if frac.max() > 0 else 1)
    ax.set_xticks(range(len(clusters)))
    ax.set_xticklabels(clusters, rotation=90)
    ax.set_yticks(range(len(top_genes)))
    ax.set_yticklabels(top_genes)
    ax.set_xlabel(cluster_key)
    ax.set_title("decontX: fraction of each gene's UMIs judged contamination, by cluster")
    fig.colorbar(im, ax=ax, label="contam_fraction_of_gene_counts")
    fig.tight_layout()
    fig.savefig(os.path.join(figdir, "decontx_heatmap_by_cluster.png"), dpi=150)
    plt.close(fig)


def _paga_table(ad, cluster_key):
    """Cluster x cluster PAGA connectivity matrix from sc.tl.paga (cluster
    connectivity computed over the KNN graph in ad.obsp["connectivities"])."""
    conn = ad.uns["paga"]["connectivities"]
    labels = ad.obs[cluster_key].cat.categories.astype(str)
    df = pd.DataFrame(conn.toarray(), index=labels, columns=labels)
    df.index.name = cluster_key
    return df


QC_OVERLAY_COLS = (
    "total_counts", "n_genes_by_counts", "pct_counts_mt", "doublet_score",
    "decontX_contamination", "pct_counts_malat1", "dissociation_score",
)


def _plot_qc_violin(ad, cluster_key, figdir):
    """One violin per QC metric grouped by cluster, one file each — color
    intensity on a UMAP is only a rough read, while these show directly
    whether a cluster deviates on some QC metric (e.g. a cluster whose median
    doublet_score/contamination is far above the rest), which point overlap
    on the UMAP easily hides."""
    qc_cols = [c for c in QC_OVERLAY_COLS if c in ad.obs]
    if not qc_cols:
        return
    print(f"== plotting QC violin by {cluster_key} -> {figdir}", flush=True)

    for col in qc_cols:
        fig, ax = plt.subplots(figsize=_PLOT_FIGSIZE)
        sc.pl.violin(ad, keys=col, groupby=cluster_key, rotation=90, stripplot=False, ax=ax, show=False)
        ax.set_title(col)
        ax.set_ylabel("")
        fig.tight_layout()
        fig.savefig(os.path.join(figdir, f"qc_violin_{_slug(col)}.png"), dpi=_PLOT_DPI)
        plt.close(fig)


def _plot_cluster_overview(ad, leiden_keys, marker_genes, figdir):
    print(f"== plotting UMAP panels -> {figdir}", flush=True)
    _save_umap_panels(ad, leiden_keys, "umap_clusters", figdir, legend_loc="on data", legend_fontsize=6)

    qc_cols = [c for c in QC_OVERLAY_COLS if c in ad.obs]
    if qc_cols:
        _save_umap_panels(ad, qc_cols, "umap_qc", figdir)

    if marker_genes:
        score_cols = []
        for name, genes in marker_genes.items():
            genes_ok = [g for g in genes if g in ad.raw.var_names]
            if not genes_ok:
                continue
            sc.tl.score_genes(ad, genes_ok, score_name=f"score_{name}", use_raw=True)
            score_cols.append(f"score_{name}")
        if score_cols:
            _save_umap_panels(ad, score_cols, "umap_markers", figdir, cmap="viridis")


def run_one_sample_pipeline(adata, sample_label=None, sample_col="sample", qc_kwargs=None, cluster_kwargs=None, outdir=None):
    """Single-sample end-to-end: QC → keep passing cells → clustering/DEG.

    qc_kwargs is forwarded verbatim to osp.qc.qc_one_sample, cluster_kwargs
    to cluster_and_deg.

    Returns (ad_final, de_df, cluster_summary_df, paga_df,
    decontx_by_cluster_df, qc_summary_dict).
    """
    qc_kwargs = dict(qc_kwargs or {})
    cluster_kwargs = dict(cluster_kwargs or {})
    qc_kwargs.setdefault("make_plots", True)
    qc_kwargs.setdefault("sample_col", sample_col)
    cluster_kwargs.setdefault("sample_col", sample_col)
    if outdir:
        qc_kwargs.setdefault("figdir", os.path.join(outdir, "qc_figures"))

    print(f"== QC ({sample_label})", flush=True)
    ad_qc, qc_summary = qc_one_sample(adata, sample_label=sample_label, **qc_kwargs)
    print(pd.Series(qc_summary), flush=True)
    ad_pass = ad_qc[~ad_qc.obs["low_quality"]].copy()

    if outdir:
        os.makedirs(outdir, exist_ok=True)
        pd.Series(qc_summary).to_csv(os.path.join(outdir, "qc_summary.csv"))
        # per-cell ledger of everything this filter drops — the only place
        # these cells leave a trace (clustered.h5ad holds survivors only);
        # every later step (msp annotate, zmip) keeps the same kind of file
        ledger_cols = [c for c in ("qc_reason", "qc_hard_fail", "qc_mad_outlier", "qc_mt_outlier",
                                   "qc_doublet", "total_counts", "n_genes_by_counts", "pct_counts_mt",
                                   "pct_counts_in_top_20_genes", "doublet_score", "decontX_contamination")
                       if c in ad_qc.obs]
        removed = ad_qc.obs.loc[ad_qc.obs["low_quality"].values, ledger_cols].copy()
        removed.insert(0, "sample", sample_label)
        removed.index.name = "cell"
        removed.to_csv(os.path.join(outdir, "qc_removed.csv"))

    print(f"== after QC: {ad_pass.shape}", flush=True)
    print("== clustering + DEG", flush=True)
    ad_final, de_df, cluster_summary, paga_df, decontx_by_cluster = cluster_and_deg(ad_pass, outdir=outdir, **cluster_kwargs)

    return ad_final, de_df, cluster_summary, paga_df, decontx_by_cluster, qc_summary
